version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development

  redis:
    image: redis:6

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - ./config/credentials.yml.enc:/app/config/credentials.yml.enc
      - ./config/master.key:/app/config/master.key
    ports:
      - "3566:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - ./config/credentials.yml.enc:/app/config/credentials.yml.enc
      - ./config/master.key:/app/config/master.key
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - web

  send_test_data:
    build: .
    command: bash -c "sleep 30 && bundle exec rails runner send_test_data.rb"
    volumes:
      - .:/app
      - ./config/credentials.yml.enc:/app/config/credentials.yml.enc
      - ./config/master.key:/app/config/master.key
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - web

volumes:
  postgres_data: