default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: water-monitor_development

test:
  <<: *default
  database: water-monitor_test

production:
  <<: *default
  database: your_app_production
  username: your_database_user
  password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>